### ISSUE TITLE
Would like an example of getting the OIDC URI for EKS.

### ISSUE THREAD

**Issue by KeithMHughesRoteraAI** [terraform-module/terraform-kubernetes-velero#11]
# Documentation Issue

## What was unclear or otherwise insufficient❓

How to get the OIDC provider URI, in particular for EKS.

## Recommended Fix

Examples for a variety of Kubernetes deployments, but in particular for EKS.

## Are you willing to resolve this issue by submitting a Pull Request❓

If someone can give me the example, sure.

- [ ] Yes, I have the time, and I know how to start.
- [x ] Yes, I have the time, but I don't know how to start. I would need guidance.
- [ ] No, I don't have the time, although I believe I could do it if I had the time...
- [ ] No, I don't have the time and I wouldn't even know how to start.

**Comment by ivankatliarchuk** [comment]
I would say it depends on which flavour of Kubernetes is in use. Created an example for `EKS` [here](https://github.com/terraform-module/terraform-kubernetes-velero/tree/master/examples/oidc
